language: java
services:
  - docker

script:
  - docker build -t openttt/openttt-backend:$TRAVIS_COMMIT

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master

jdk:
  oracledjdk11