language: java

addons:
  sonarcloud:
    organization: "openttt"
    token:
      secure: $SONAR_TOKEN


script:
  # Needed for sonarqube
  - git fetch --unshallow
  - mvn org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

jdk:
  oracledjdk11
