language: java
services:
  - docker
addons:
  sonarcloud:
    organization: "openttt"
    token:
      secure: $SONAR_TOKEN


script:
  # Needed for sonarqube
  - git fetch --unshallow
  - mvn org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
  - docker build . -t openttt/openttt-backend

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master

jdk:
  oracledjdk11
