language: java
services:
  - docker
addons:
  sonarcloud:
    organization: "openttt" # the key of the org you chose at step #3
    token:
      secure: $SONAR_TOKEN


script:
  - mvn sonar:sonar
  - docker build . -t openttt/openttt-backend

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master

jdk:
  oracledjdk11
