spring:
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    hibernate:
      ddl-auto: update
    # The following properties will be set by the runtime at AWS
    url: ""
    username: ""
    password: ""